# Random Sampling

In [1]:
import numpy as np

In [2]:
np.__version__

'1.23.5'

In [5]:
__author__ = 'kyubyong. longinglove@nate.com'

## Simple random data

Q1. Create an array of shape (3, 2) and populate it with random samples from a uniform distribution over [0, 1).

In [6]:
rng = np.random.default_rng()
rng.random((3,2))

array([[0.63464374, 0.17867018],
       [0.7566867 , 0.12497649],
       [0.02069695, 0.0167235 ]])

array([[ 0.13879034,  0.71300174],
       [ 0.08121322,  0.00393554],
       [ 0.02349471,  0.56677474]])

Q2. Create an array of shape (1000, 1000) and populate it with random samples from a standard normal distribution. And verify that the mean and standard deviation is close enough to 0 and 1 repectively.

In [19]:
mu, sigma = 0, 1

s = mu + sigma * rng.standard_normal((1000, 1000))
s

array([[ 1.17983813, -0.55464691,  0.45023938, ...,  0.68814973,
        -0.57898562, -0.0088466 ],
       [-0.78710511,  0.54276611,  0.56667447, ..., -1.51424613,
        -0.23334537, -0.56908035],
       [-0.28392452, -1.31617996, -1.11679435, ..., -0.41527178,
        -1.72226557,  2.30245181],
       ...,
       [-0.89076136,  1.27552309,  0.60474635, ..., -1.68306367,
         0.9165051 ,  0.12816287],
       [ 1.40758347,  1.47204251, -0.43184543, ...,  0.32058888,
        -1.07056002, -0.40125345],
       [ 0.80042082, -0.04003161,  1.40154006, ..., -0.41755296,
         0.56408633, -1.08536436]])

In [20]:
s.shape

(1000, 1000)

-0.00110028519551
0.999683483393


Q3. Create an array of shape (3, 2) and populate it with random integers ranging from 0 to 3 (inclusive) from a discrete uniform distribution.

In [21]:
rng = np.random.default_rng()
rng

Generator(PCG64) at 0x1E765699A80

In [24]:
x = rng.integers(4, size=(3, 2))
x

array([[1, 0],
       [3, 2],
       [3, 3]], dtype=int64)

array([[1, 3],
       [3, 0],
       [0, 0]])

Q4. Extract 1 elements from x randomly such that each of them would be associated with probabilities .3, .5, .2. Then print the result 10 times.

In [3]:
x = [b'3 out of 10', b'5 out of 10', b'2 out of 10']


5 out of 10
2 out of 10
3 out of 10
5 out of 10
2 out of 10
5 out of 10
2 out of 10
2 out of 10
2 out of 10
5 out of 10


Q5. Extract 3 different integers from 0 to 9 randomly with the same probabilities.

array([5, 4, 0])

## Permutations

Q6. Shuffle numbers between 0 and 9 (inclusive).

In [28]:
rng = np.random.default_rng()
x = rng.permutation(10)
x

array([0, 5, 8, 9, 2, 1, 4, 3, 6, 7])

[2 3 8 4 5 1 0 6 9 7]


In [88]:
# Or


[5 2 7 4 1 0 6 8 9 3]


## Random generator

Q7. Assign number 10 to the seed of the random generator so that you can get the same value next time.

In [35]:
rng = np.random.default_rng()
rng

Generator(PCG64) at 0x1E765699FC0

In [36]:
rng = np.random.default_rng(seed=10)
x = rng.permutation(10)
x

array([1, 3, 2, 4, 7, 9, 5, 6, 0, 8])

In [37]:
rng = np.random.default_rng(seed=10)
x = rng.permutation(10)
x

array([1, 3, 2, 4, 7, 9, 5, 6, 0, 8])