# Soring, searching, and counting

In [1]:
import numpy as np

In [3]:
np.__version__

'1.23.5'

In [4]:
author = 'kyubyong. longinglove@nate.com'

## Sorting

Q1. Sort x along the second axis.

In [6]:
x = np.array([[1,4],[3,1]])
x


array([[1, 4],
       [3, 1]])

In [7]:
np.sort(x, axis=1)

array([[1, 4],
       [1, 3]])

Q2. Sort pairs of surnames and first names and return their indices. (first by surname, then by name).

In [8]:
surnames =    ('Hertz',    'Galilei', 'Hertz')
first_names = ('Heinrich', 'Galileo', 'Gustav')


In [9]:
np.lexsort((first_names, surnames))

array([1, 2, 0], dtype=int64)

Q3. Get the indices that would sort x along the second axis.

In [11]:
x = np.array([[1,4],[3,1]])
x


array([[1, 4],
       [3, 1]])

In [18]:
np.argsort(x, axis=1)

array([[0, 1],
       [1, 0]], dtype=int64)

Q4. Create an array such that its fifth element would be the same as the element of sorted x, and it divide other elements by their value.

In [30]:
x = np.random.permutation(10)
print ("x = ", x)


x =  [4 2 5 3 8 1 9 6 7 0]


In [37]:
x = np.array([5, 1, 6, 3, 9, 8, 2, 7, 4, 0])

In [38]:
# np.array(x)[np.argpartition(x, kth=5)]
np.partition(x, 5)

array([2, 0, 4, 3, 1, 5, 8, 7, 6, 9])

Q5. Create the indices of an array such that its third element would be the same as the element of sorted x, and it divide other elements by their value.

In [39]:
x = np.random.permutation(10)
print ("x =", x)


x = [0 1 4 8 5 7 9 6 3 2]


In [40]:
x = np.array([2, 8, 3, 7, 5, 6, 4, 0, 9, 1])
x

array([2, 8, 3, 7, 5, 6, 4, 0, 9, 1])

In [42]:
x[np.argpartition(x, 5)]

array([0, 1, 2, 3, 4, 5, 8, 6, 9, 7])

## Searching

Q6. Get the maximum and minimum values and their indices of x along the second axis.

In [78]:
x = np.random.permutation(10).reshape(2, 5)
print( "x =", x)


x = [[0 5 9 8 2]
 [3 7 4 1 6]]
maximum values = [9 7]
max indices = [2 1]
minimum values = [0 1]
min indices = [0 3]


In [49]:
x = np.array([[0, 5, 9, 8, 2],
            [3, 7, 4, 1, 6]])
print("x = ", x)
print("maximum values = ", np.max(x, axis=1))
print("maximum indices = ", np.argmax(x, axis=1))
print("minimum values = ", np.min(x, axis=1))
print("minimum indices = ", np.argmin(x, axis=1))


x =  [[0 5 9 8 2]
 [3 7 4 1 6]]
maximum values =  [9 7]
maximum indices =  [2 1]
minimum values =  [0 1]
minimum indices =  [0 3]


Q7. Get the maximum and minimum values and their indices of x along the second axis, ignoring NaNs.

In [51]:
x = np.array([[np.nan, 4], [3, 2]])
x

array([[nan,  4.],
       [ 3.,  2.]])

In [55]:
print("maximum values ignoring NaNs = ", np.nanmax(x, 1))
print("max indices = ", np.nanargmax(x, 1))
print("minimum values ignoring NaNs = ", np.nanmin(x, 1))
print("min indices = ", np.nanargmin(x, 1))

maximum values ignoring NaNs =  [4. 3.]
max indices =  [1 0]
minimum values ignoring NaNs =  [4. 2.]
min indices =  [1 1]


Q8. Get the values and indices of the elements that are bigger than 2 in x.


In [57]:
x = np.array([[1, 2, 3], [1, 3, 5]])
x

array([[1, 2, 3],
       [1, 3, 5]])

In [66]:
print("Values bigger than 2 = ", np.where(x>2))
print("Their indices are ", np.argwhere(x>2))

Values bigger than 2 =  (array([0, 1, 1], dtype=int64), array([2, 1, 2], dtype=int64))
Their indices are  [[0 2]
 [1 1]
 [1 2]]


Q9. Get the indices of the elements that are bigger than 2 in the flattend x.

In [106]:
x = np.array([[1, 2, 3], [1, 3, 5]])
x

array([[1, 2, 3],
       [1, 3, 5]])

In [110]:
y = x.flatten()
print(np.argwhere(y>2))

[[2]
 [4]
 [5]]


Q10. Check the elements of x and return 0 if it is less than 0, otherwise the element itself.

In [92]:
x = np.arange(-5, 4).reshape(3, 3)
x

array([[-5, -4, -3],
       [-2, -1,  0],
       [ 1,  2,  3]])

In [102]:
np.where(x.flatten() < 0, x.flatten() * 0, x.flatten()).reshape(3, 3)

array([[0, 0, 0],
       [0, 0, 0],
       [1, 2, 3]])

Q11. Get the indices where elements of y should be inserted to x to maintain order.

In [109]:
x = [1, 3, 5, 7, 9]
y = [0, 4, 2, 6]


array([0, 2, 1, 3], dtype=int64)

In [111]:
x = [1, 3, 5, 7, 9]
y = [0, 4, 2, 6]

np.searchsorted(x, y)

array([0, 2, 1, 3], dtype=int64)

## Counting

Q12. Get the number of nonzero elements in x.

In [112]:
x = [[0,1,7,0,0],[3,0,0,2,19]]
np.count_nonzero(x)

5