# Array manipulation routines

In [1]:
import numpy as np

In [2]:
np.__version__

'1.23.5'

Q1. Let x be a ndarray [10, 10, 3] with all elements set to one. Reshape x so that the size of the second dimension equals 150.

In [3]:
np.ones((3, 10, 10)).reshape(-1, 150)

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1.,

Q2. Let x be array [[1, 2, 3], [4, 5, 6]]. Convert it to [1 4 2 5 3 6].

In [4]:
x = np.array([[1, 2, 3], [4, 5, 6]])
x

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
x.flatten()

array([1, 2, 3, 4, 5, 6])

Q3. Let x be array [[1, 2, 3], [4, 5, 6]]. Get the 5th element.

In [6]:
x = np.array([[1, 2, 3], [4, 5, 6]]).flatten()[5]
x

6

Q4. Let x be an arbitrary 3-D array of shape (3, 4, 5). Permute the dimensions of x such that the new shape will be (4,3,5).


In [7]:
x = np.ndarray((3, 4, 5), dtype=int)
x

array([[[1634929944,        506,        207,          0,          0],
        [         0,          0,          0,          0,    6357084],
        [1936532091, 1684627303,  572537378,  943208241,  828584761],
        [ 943023661,  912602422, 1647732017, 1647797296, 1700869687]],

       [[ 811938145,  926048099, 1597518386,  740439091, 1936532000],
        [2037669735,  975332720, 1953702432, 1937077345,  572533794],
        [1919251317, 1701667182,  572537378, 1919251317, 1701667182],
        [ 572533794, 1936942451,  577662825,  824320058,  959985719]],

       [[ 758211379,  909653350,  825648437,  811742821,  929183588],
        [1634033974, 1664116017,  572533794, 1702125924,  572537378],
        [ 875704370,  758525997,  827601712,  909392436,  775041594],
        [ 825636660,  576338228, 1981947948, 1769173605,  975335023]]])

In [8]:
x.shape

(3, 4, 5)

In [9]:
x.reshape((4, 3, 5))

array([[[1634929944,        506,        207,          0,          0],
        [         0,          0,          0,          0,    6357084],
        [1936532091, 1684627303,  572537378,  943208241,  828584761]],

       [[ 943023661,  912602422, 1647732017, 1647797296, 1700869687],
        [ 811938145,  926048099, 1597518386,  740439091, 1936532000],
        [2037669735,  975332720, 1953702432, 1937077345,  572533794]],

       [[1919251317, 1701667182,  572537378, 1919251317, 1701667182],
        [ 572533794, 1936942451,  577662825,  824320058,  959985719],
        [ 758211379,  909653350,  825648437,  811742821,  929183588]],

       [[1634033974, 1664116017,  572533794, 1702125924,  572537378],
        [ 875704370,  758525997,  827601712,  909392436,  775041594],
        [ 825636660,  576338228, 1981947948, 1769173605,  975335023]]])

Q5. Let x be an arbitrary 2-D array of shape (3, 4). Permute the dimensions of x such that the new shape will be (4,3).

In [10]:
x = np.ndarray((3, 4), dtype=int)
x

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [11]:
x.transpose()

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

Q5. Let x be an arbitrary 2-D array of shape (3, 4). Insert a nex axis such that the new shape will be (3, 1, 4).

In [12]:
x = np.ndarray((3, 4), dtype=int)
x

array([[4128860, 6029375, 3801155, 5570652],
       [6619251, 7536754, 4259932, 5046340],
       [5111881, 4259932, 7340144, 6357060]])

In [13]:
x.reshape(3, 1, 4)

array([[[4128860, 6029375, 3801155, 5570652]],

       [[6619251, 7536754, 4259932, 5046340]],

       [[5111881, 4259932, 7340144, 6357060]]])

Q6. Let x be an arbitrary 3-D array of shape (3, 4, 1). Remove a single-dimensional entries such that the new shape will be (3, 4).

In [14]:
x = np.ndarray((3, 4, 1), dtype=int)
x

array([[[0],
        [0],
        [0],
        [0]],

       [[0],
        [0],
        [0],
        [0]],

       [[0],
        [0],
        [0],
        [0]]])

In [15]:
x.reshape(3, -1)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [16]:
x.reshape(3, -1).shape

(3, 4)

Q7. Lex x be an array <br/>
[[ 1 2 3]<br/>
[ 4 5 6].<br/><br/>
and y be an array <br/>
[[ 7 8 9]<br/>
[10 11 12]].<br/>
Concatenate x and y so that a new array looks like <br/>[[1, 2, 3, 7, 8, 9], <br/>[4, 5, 6, 10, 11, 12]].


In [17]:
x = np.array([[1, 2, 3], [4, 5, 6]])
y = np.array([[7, 8, 9], [10, 11, 12]])

In [18]:
np.concatenate([x, y], axis=1)

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

Q8. Lex x be an array <br/>
[[ 1 2 3]<br/>
[ 4 5 6].<br/><br/>
and y be an array <br/>
[[ 7 8 9]<br/>
[10 11 12]].<br/>
Concatenate x and y so that a new array looks like <br/>[[ 1  2  3]<br/>
 [ 4  5  6]<br/>
 [ 7  8  9]<br/>
 [10 11 12]]


In [19]:
np.concatenate([x, y], axis=0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

Q8. Let x be an array [1 2 3] and y be [4 5 6]. Convert it to [[1, 4], [2, 5], [3, 6]].

In [20]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
np.concatenate([x, y]).reshape(3, 2)

array([[1, 2],
       [3, 4],
       [5, 6]])

Q9. Let x be an array [[1],[2],[3]] and y be [[4], [5], [6]]. Convert x to [[[1, 4]], [[2, 5]], [[3, 6]]].

In [21]:
x = np.array([[[1], [2], [3]]])
y = np.array([[[4], [5], [6]]])
z = np.concatenate([x, y], axis=2)
z

array([[[1, 4],
        [2, 5],
        [3, 6]]])

In [22]:
x = np.array([[[1], [2], [3]]])
y = np.array([[[4], [5], [6]]])
z = np.concatenate([x, y], axis=2).reshape(3, 2, 1)
z

array([[[1],
        [4]],

       [[2],
        [5]],

       [[3],
        [6]]])

Q10. Let x be an array [1, 2, 3, ..., 9]. Split x into 3 arrays, each of which has 4, 2, and 3 elements in the original order.

In [23]:
x = np.arange(1, 10)
x


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
z = np.split(x, [4, 6, 10])
z

[array([1, 2, 3, 4]), array([5, 6]), array([7, 8, 9]), array([], dtype=int32)]

Q11. Let x be an array<br/>
[[[  0.,   1.,   2.,   3.],<br/>
  [  4.,   5.,   6.,   7.]],<br/>
 
 [[  8.,   9.,  10.,  11.],<br/>
  [ 12.,  13.,  14.,  15.]]].<br/>
Split it into two such that the first array looks like<br/>
[[[  0.,   1.,   2.],<br/>
  [  4.,   5.,   6.]],<br/>
 
 [[  8.,   9.,  10.],<br/>
  [ 12.,  13.,  14.]]].<br/>
  
and the second one look like:<br/>
  
[[[  3.],<br/>
  [  7.]],<br/>
 
 [[  11.],<br/>
  [ 15.]]].<br/>  

In [25]:
x = np.array([[[0., 1., 2., 3.], [4., 5., 6., 7.]], [[8., 9., 10., 11.], [12., 13., 14. ,15.]]])
x

array([[[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.]],

       [[ 8.,  9., 10., 11.],
        [12., 13., 14., 15.]]])

In [26]:
np.dsplit(x, 2)

[array([[[ 0.,  1.],
         [ 4.,  5.]],
 
        [[ 8.,  9.],
         [12., 13.]]]),
 array([[[ 2.,  3.],
         [ 6.,  7.]],
 
        [[10., 11.],
         [14., 15.]]])]

In [27]:
np.dsplit(x, np.array([3, 6]))

[array([[[ 0.,  1.,  2.],
         [ 4.,  5.,  6.]],
 
        [[ 8.,  9., 10.],
         [12., 13., 14.]]]),
 array([[[ 3.],
         [ 7.]],
 
        [[11.],
         [15.]]]),
 array([], shape=(2, 2, 0), dtype=float64)]

Q12. Let x be an array <br />
[[  0.,   1.,   2.,   3.],<br>
 [  4.,   5.,   6.,   7.],<br>
 [  8.,   9.,  10.,  11.],<br>
 [ 12.,  13.,  14.,  15.]].<br>
Split it into two arrays along the second axis.

In [28]:
# [array([[ 0,  1],
#        [ 4,  5],
#        [ 8,  9],
#        [12, 13]]),
# array([[ 2,  3],
#        [ 6,  7],
#        [10, 11],
#        [14, 15]])]

# [array([[ 0,  2],
#        [ 4,  6],
#        [ 8,  10],
#        [12, 14]]),
# array([[ 1,  3],
#        [ 5,  7],
#        [9, 11],
#        [13, 15]])]

# [array([[ 0,  2, 1, 3],
#        [ 4,  6, 5, 7],
#        [ 8,  10, 9, 11],
#        [12, 14, 13, 15]]),
x = np.array([[0., 1., 2., 3.], [4., 5., 6., 7.], [8., 9., 10., 11.], [12., 13., 14. ,15.]])
x

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.],
       [12., 13., 14., 15.]])

In [29]:
x.reshape((8, 2)).transpose(1, 0)

array([[ 0.,  2.,  4.,  6.,  8., 10., 12., 14.],
       [ 1.,  3.,  5.,  7.,  9., 11., 13., 15.]])

In [30]:
np.split(x, 2, axis=-1)

[array([[ 0.,  1.],
        [ 4.,  5.],
        [ 8.,  9.],
        [12., 13.]]),
 array([[ 2.,  3.],
        [ 6.,  7.],
        [10., 11.],
        [14., 15.]])]

In [31]:
[x[:, :2], x[:, 2:]]

[array([[ 0.,  1.],
        [ 4.,  5.],
        [ 8.,  9.],
        [12., 13.]]),
 array([[ 2.,  3.],
        [ 6.,  7.],
        [10., 11.],
        [14., 15.]])]

Q13. Let x be an array <br />
[[  0.,   1.,   2.,   3.],<br>
 [  4.,   5.,   6.,   7.],<br>
 [  8.,   9.,  10.,  11.],<br>
 [ 12.,  13.,  14.,  15.]].<br>
Split it into two arrays along the first axis.

In [32]:
x = np.array([[0., 1., 2., 3.], [4., 5., 6., 7.], [8., 9., 10., 11.], [12., 13., 14. ,15.]])
x

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.],
       [12., 13., 14., 15.]])

In [33]:
np.vsplit(x, 2)


[array([[0., 1., 2., 3.],
        [4., 5., 6., 7.]]),
 array([[ 8.,  9., 10., 11.],
        [12., 13., 14., 15.]])]

Q14. Let x be an array [0, 1, 2]. Convert it to <br/>
[[0, 1, 2, 0, 1, 2],<br/>
 [0, 1, 2, 0, 1, 2]].

In [34]:
x = np.array([0, 1, 2])
x

array([0, 1, 2])

In [35]:
np.tile(x, 2)

array([0, 1, 2, 0, 1, 2])

In [36]:
np.tile(x, (2, 2))

array([[0, 1, 2, 0, 1, 2],
       [0, 1, 2, 0, 1, 2]])

Q15. Let x be an array [0, 1, 2]. Convert it to <br/>
[0, 0, 1, 1, 2, 2].

In [37]:
x = np.array([0, 1, 2])
x

array([0, 1, 2])

In [38]:
np.repeat(x, 2)

array([0, 0, 1, 1, 2, 2])

Q16. Let x be an array [0, 0, 0, 1, 2, 3, 0, 2, 1, 0].<br/>
remove the leading the trailing zeros.

In [39]:
x = np.array([0, 0, 0, 1, 2, 3, 0, 2, 1, 0])
x

array([0, 0, 0, 1, 2, 3, 0, 2, 1, 0])

In [40]:
np.trim_zeros(x)

array([1, 2, 3, 0, 2, 1])

Q17. Let x be an array [2, 2, 1, 5, 4, 5, 1, 2, 3]. Get two arrays of unique elements and their counts.


In [41]:
x = np.array([2, 2, 1, 5, 4, 5, 1, 2, 3])
x

array([2, 2, 1, 5, 4, 5, 1, 2, 3])

In [42]:
np.unique(x,return_counts=True)

(array([1, 2, 3, 4, 5]), array([2, 3, 1, 1, 2], dtype=int64))

Q18. Lex x be an array <br/>
[[ 1 2]<br/>
 [ 3 4].<br/>
Flip x along the second axis.

In [43]:
x = np.array([[1, 2], [3, 4]])
x

array([[1, 2],
       [3, 4]])

In [46]:
np.flip(x, 1)

array([[2, 1],
       [4, 3]])

Q19. Lex x be an array <br/>
[[ 1 2]<br/>
 [ 3 4].<br/>
Flip x along the first axis.

In [47]:
x = np.array([[1, 2], [3, 4]])
x

array([[1, 2],
       [3, 4]])

In [48]:
np.flip(x, 0)

array([[3, 4],
       [1, 2]])

Q20. Lex x be an array <br/>
[[ 1 2]<br/>
 [ 3 4].<br/>
Rotate x 90 degrees counter-clockwise.

In [51]:
x = np.arange(1, 5).reshape((2, -1))
x

array([[1, 2],
       [3, 4]])

In [52]:
np.rot90(x)

array([[2, 4],
       [1, 3]])

Q21 Lex x be an array <br/>
[[ 1 2 3 4]<br/>
 [ 5 6 7 8].<br/>
Shift elements one step to right along the second axis.

In [54]:
x = np.arange(1, 9).reshape((2, -1))
x

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [65]:
np.roll(x, -3, axis=1)

array([[4, 1, 2, 3],
       [8, 5, 6, 7]])